POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Mtuan",
  "age": 25,
  "sex": "male",
  "height": 180,
  "weight": 75
}

###
DELETE http://localhost:3001/api/user/4

###


